import Head from "next/head";
import Image from "next/image";
import { Hero } from "./components/Hero/Hero";
import { ProjectsCompleted } from "./components/Hero/ProjectCompleted";
import { Services } from "./components/Hero/Services";
import { TopStories } from "./components/Hero/TopStories";
import { Wally } from "./components/Hero/Wally";
import { ProudOf } from "./components/ProudOf";
import { Team } from "./components/Team";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <ProjectsCompleted className="home-page" />
      <Wally title={true} />
      <Services />

      <TopStories />
      <ProudOf title={true} />
      <Team title={false} />
    </div>
  );
}
