import Head from "next/head";
import {
  Hero,
  Layout,
  ProudOf,
  Services,
  Team,
  TopStories,
} from "../components";
import { Process } from "../components/Hero/Process";
import ProjectsCompleted from "../components/Hero/ProjectCompleted";
import Wally from "../components/Hero/Wally";
import TestimonialSlider from "../components/TestimonialSlider";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Services />

      <ProjectsCompleted className="home-page" />

      <TopStories />
      <Wally title={true} />
      <ProudOf title={true} />
      <TestimonialSlider />
      <Team title={false} />
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
